/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AI-scan` | `/AI-scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Nutrition` | `/Nutrition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | { pathname: `/NutritionControl/NutritionPlan`; params?: Router.UnknownInputParams; } | { pathname: `/NutritionControl/NutritionSearch`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signDetails1`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signDetails2`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signDetails3`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/UserContext`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AI-scan` | `/AI-scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Nutrition` | `/Nutrition`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownOutputParams; } | { pathname: `/NutritionControl/NutritionPlan`; params?: Router.UnknownOutputParams; } | { pathname: `/NutritionControl/NutritionSearch`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/signDetails1`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/signDetails2`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/signDetails3`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/UserContext`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AI-scan${`?${string}` | `#${string}` | ''}` | `/AI-scan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Nutrition${`?${string}` | `#${string}` | ''}` | `/Nutrition${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workout${`?${string}` | `#${string}` | ''}` | `/workout${`?${string}` | `#${string}` | ''}` | `/NutritionControl/NutritionPlan${`?${string}` | `#${string}` | ''}` | `/NutritionControl/NutritionSearch${`?${string}` | `#${string}` | ''}` | `/authentication/login${`?${string}` | `#${string}` | ''}` | `/authentication/signDetails1${`?${string}` | `#${string}` | ''}` | `/authentication/signDetails2${`?${string}` | `#${string}` | ''}` | `/authentication/signDetails3${`?${string}` | `#${string}` | ''}` | `/authentication/signUp${`?${string}` | `#${string}` | ''}` | `/contexts/UserContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AI-scan` | `/AI-scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Nutrition` | `/Nutrition`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | { pathname: `/NutritionControl/NutritionPlan`; params?: Router.UnknownInputParams; } | { pathname: `/NutritionControl/NutritionSearch`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signDetails1`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signDetails2`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signDetails3`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/UserContext`; params?: Router.UnknownInputParams; };
    }
  }
}
